### ISSUE TITLE
Jedi-vim failing to start

### ISSUE THREAD

**Issue by tuetschek** [davidhalter/jedi-vim#1005]
### Issue

After I upgraded both my system and Jedi-vim, Jedi-vim stopped working completely. Running the tests inside my Jedi-vim checkout using the `py.test` command fails. My system is Pengwin WSL with Python 3.7.7 and Vim 8.1 compiled with Python 3.8.2.

The tests first fail with:
```
Traceback (most recent call last):
  File "/home/ondra/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 194, in wrapper
    return func(*args, **kwargs)
  File "/home/ondra/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 274, in get_script
    environment=get_environment(),
  File "/home/ondra/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 226, in get_environment
    environment = jedi.api.environment.get_cached_default_environment()
AttributeError: module 'jedi.api' has no attribute 'environment'
Traceback (most recent call last):
  File "/home/ondra/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 307, in completions
    completions = script.completions()
AttributeError: 'NoneType' object has no attribute 'completions'
=jedi#complete_opened(0)
not ok 3 - completions import
```

I'm attaching the full output of the tests here: [tests_output.txt](https://github.com/davidhalter/jedi-vim/files/4381024/tests_output.txt) – that includes the Jedi-vim debug info.

Is there something wrong with my setup?

**Comment by davidhalter** [comment]
Your version of Jedi is probably too old, initialize your jedi-vim directy with `git submodule update --init`.

Also:

You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since You have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information.

**Comment by tuetschek** [comment]
I just made a fresh checkout and that fixed it – it must have been the submodule version mismatch. Thank you! And I'm sorry about the form.
