### ISSUE TITLE
I plugged in jedi-vim Open .py file, nothing happened while writing code?

### ISSUE THREAD

**Issue by LaxmanMaharjan** [davidhalter/jedi-vim#1055]
### Issue

I plugged in jedi-vim Open .py file, nothing happened while writing code?
I am supposed to do anything else after plugging in jedi-vim

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since You have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information.
