### ISSUE TITLE
how to reduce size of autocomplete suggestions window?

### ISSUE THREAD

**Issue by BorageShtrowtsky** [davidhalter/jedi-vim#1056]
The autocomplete suggestions window is too big and I want to reduce its size by default. How do I do this?

Here are my current Jedi options:
```python
let g:jedi#use_splits_not_buffers = "left"

let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_stubs_command = "<leader>s"
let g:jedi#goto_definitions_command = "<C-]>"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>r"
```
I'am asking because when I'm using big modules, the autocomplete window will completely cover off the rest of the file.

**Comment by davidhalter** [comment]
I have no idea. Not sure if anyone else can help you. Generally this is not something that jedi-vim influences. This is something that you have to change in VIM. I suggest you start tuning `:help completeopt` and see where you land.

Closing, because this is not something that jedi-vim really affects or that we could change.
