### ISSUE TITLE
vim load the jedi-vim occur the error:Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: Traceback (most recent call last): (in function  jedi#init_python[4]..<SNR>51_init_python[6]..jedi#setup_python_imports, line 20). See :messages and/or :JediDebugInfo fo r more information.

### ISSUE THREAD

**Issue by summerccc** [davidhalter/jedi-vim#1063]

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information.

**Comment by sedeki** [comment]
This happens to me also, specifically when I set `language en_US`.

**Comment by davidhalter** [comment]
Please open a new issue. The original post forgot to actually provide details, so I wasn't able to help.
