### ISSUE TITLE
not working jedi in neowim

### ISSUE THREAD

**Issue by grisha765** [davidhalter/jedi-vim#1080]
https://imgur.com/Gjn2dXf.png
https://imgur.com/a5Y9qm9.png

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since You have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information.
