### ISSUE TITLE
Find Chinese name  definition will report error and stop

### ISSUE THREAD

**Issue by fhopecc** [davidhalter/jedi-vim#1085]
I use Chinese Name for function definition for others to maintain code, but if I use \<leader\>d to find the Chinese Name definition, it will report ValueError and stop. (ex. find the "轉半型" function definition as following screenshot).

Maybe it  is because Chinese Name is composed of wide chars, and vim get cursor positon function take a wide char length as 2, but Jedi-python take as 1. 

![image](https://user-images.githubusercontent.com/61467/164576577-b73ecfe9-dc14-4ba0-b3ac-0d5cf76785c2.png)

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since You have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information (just click the New Issue Button and you'll find it there).
