### ISSUE TITLE
autocompletion not working with python3 modules

### ISSUE THREAD

**Issue by harsh7i** [davidhalter/jedi-vim#1099]
### Issue
I have installed a `pip` module called `pytube` without `pip`.I used `pytube` tar ball to install it. but now there is no `pytube` in autocompletion.
![IMG_20221228_112442](https://user-images.githubusercontent.com/100824266/209764820-792a9745-2645-4c7c-9bf0-470f7d455c95.jpg)

### Steps to reproduce
I have latest version of `git` and `jedi-vim`.
I installed `jedi-vim` with `Vundle`, I didn't use `pip install jedi`.
Just download a tar ball from `pypi` website. And install it with `sudo python3 setup.py install`.

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information (just click the New Issue Button and you'll find it there).
