### ISSUE TITLE
Python path for g:jedi#environment_path

### ISSUE THREAD

**Issue by zen3gr** [davidhalter/jedi-vim#1101]
Hello everyone, I have a question regarding variable g:jedi#environment_path.
I would like to set the path for the python.exe file to C:\Users\antonisg\AppData\Local\Programs\Python\Python39\python. I tried to achieve that by executing in vim: " let g:jedi#environment_path = 'C:\\Users\\antonisg\\AppData\\Local\\Programs\\Python\\Python39\\python' ", after doing that and pressing shift-k on a python command to access the documentation I get the following errors (https://imgur.com/a/fHPjQ6B). 

I think that jedi-vim adds the "\Scripts\python.exe" to the supplied path. My "python.exe" files is exactly in C:\Users\antonisg\AppData\Local\Programs\Python\Python39\python. I tried editing the following line
         python = os.path.join(path, 'Scripts', 'python.exe') to
        python = os.path.join(path, '\python.exe')
in order to have jedi looking at C:\Users\antonisg\AppData\Local\Programs\Python\Python39\python
at the jedi-vim's folder "environment.py", but with no luck.

My question is how to make sure that jedi-vim looks just in the directory I'm giving as input. Thanks in advance.

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. We don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions.

We are happy to reopen this issue if you add the necessary debug information (just click the `New Issue Button` and you'll find it there).
