### ISSUE TITLE
best practices working with virtualenv 

### ISSUE THREAD

**Issue by st203** [davidhalter/jedi-vim#1102]
Hello - I have installed Jedi-vim using vundle and it works fine. I also ran pip install jedi. I have noticed the plugin still works when inside a virtual environment created using virtualenv even though I did not run pip install jedi there. Is that normal?  What is the best practice?

Great project, keep up the good work btw!

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. We don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions.

We are happy to reopen this issue if you add the necessary debug information (just click the `New Issue Button` and you'll find it there).
