### ISSUE TITLE
It gives the issue that the package does'nt contain the version something file.

### ISSUE THREAD

**Issue by PurpleIndex** [davidhalter/jedi-vim#1104]

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. We don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions.

We are happy to reopen this issue if you add the necessary debug information (just click the `New Issue Button` and you'll find it there).
