### ISSUE TITLE
Need always autocompletion instead of only after dot

### ISSUE THREAD

**Issue by OurCodeBase** [davidhalter/jedi-vim#1107]
### Issue
By default jedi-vim is working only after a dot or we have to trigger it manually using Ctrl+Space.
I need automatically autocompletion of variables and all keywords used in python. I need autocompletion at all the time like lsp instead of only after dot.

**Comment by davidhalter** [comment]
There are various ways to do that. The one I'm using still works for me: https://github.com/ervandew/supertab

But I'm not sure that's how most people do this today. Some people also use https://github.com/deoplete-plugins/deoplete-jedi. Since omnicompletion in VIM is on `C-X C-O`, you can just remap that to wherever.
