### ISSUE TITLE
How disable?

### ISSUE THREAD

**Issue by ghost** [davidhalter/jedi-vim#1113]
![Screenshot_20230828-222726_Termux](https://github.com/davidhalter/jedi-vim/assets/142758388/3f3faa7f-6923-479c-af07-99a0a1f2085b)

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. We don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions.

We are happy to reopen this issue if you add the necessary debug information (just click the `New Issue Button` and you'll find it there).
