### ISSUE TITLE
Popups that cover a would-be autocompleted word prevent it from being autocompleted properly

### ISSUE THREAD

**Issue by mooreye** [davidhalter/jedi-vim#1119]
Example - create a file like so:

```python
#!/usr/bin/env python3

foobar = "string"
len()
```

then type `f` inside the `()` and press `Ctrl+N` (or `Tab` if using supertab plugin). It will complete `fo` instead of `foobar`, probably because the popup covers the line with `foobar` and Neovim doesn't see it. It looks like this:

![2024-02-08T14:41:41,676588692+01:00](https://github.com/davidhalter/jedi-vim/assets/93423596/3a66cd54-136f-43e6-91bf-62c1dc7d15db)

Workaround is to set
`autocmd FileType python setlocal completeopt-=preview`
but is it possible to still have popups and autocompletion work correctly?

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. We don't have enough information to debug your issue. Since you have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions.

We are happy to reopen this issue if you add the necessary debug information (just click the `New Issue Button` and you'll find it there).
