### ISSUE TITLE
How about joining up for Python code completion? (YouCompleteMe)

### ISSUE THREAD

**Issue by Valloric** [davidhalter/jedi-vim#119]
[Replicating our private email discussion in a more public forum]

I'm the author of a [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) (YCM), a recently released (Feb 2013) OSS code completion system for Vim. It's become very popular very quickly (~1300 stars on GitHub).

YCM comes with out-of-the box support for semantic completion for C-family languages like C/C++/Objective-C/Objective-C++ (using libclang as the engine) and also has a language-agnostic identifier completer. The GIF on the project page is a thousand words and there's also an extensive introduction there so I'll spare you the details that you can easily grab.

Getting to the point, an external developer contributed [a Jedi-based semantic completer](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/completers/python/jedi_completer.py) for YCM today. YCM actually provides [a generic framework for writing custom semantic completers](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/completers/completer.py) (for any language) that can then take advantage of the code completion infrastructure that YCM provides (non-blocking operation that lets Vim continue to process events, a smart caching layer, the subsequence-based completion filtering system and the advanced completion ranking algorithm etc). You can see just how small the file for jedi-based semantic Python completion is in YCM. 

I see that Jedi (which is freaking awesome btw, congrats on that) also has other features too, like goto etc. Any chance on us teaming up to bring those features to YCM? I see that you have written the jedi-vim plugin. While I haven't tried it I'm sure it's awesome (hey, it's using Jedi) but I think it's sad that we have this duplication of work. I'd also like to see YCM become a common framework for code completion in Vim, much like Syntastic is the common framework for displaying compilation/lint errors.

YCM will expand into more IDE features with go-to-definition/declaration. Basically all the useful features that one can build when one has an engine that provides a semantic understanding of the codebase. These features would be accessed through the new `:YcmCompleter [completer sub-command] [sub-command arguments]` interface that also recently landed. That command calls [OnUserCommand](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/completers/completer.py#L250) on the Completer object with the arguments the user provided after the sub-command name. From then on, the Completer writer can do anything he wishes.

So my idea is to expand the functionality of YCM's jedi_completer until it does everything jedi-vim can. That's it. I'll probably end up doing all this myself if no one else does but I'd love it if you could contribute pull-requests. Correct me if I'm wrong, but your goal is to build the best possible Python code completion system. You shouldn't have to spend time on the VimScript parts and other Vim plugin boilerplate. You should be able to focus on making Jedi, the library, even better.

If you're not interested, that's perfectly fine. I just think it's sad that there's this duplication of efforts; I spent a ton of time writing the ycm_core library in C++ so that completions in Vim can be super-fast. I'd love to see others leverage that work to improve editing in Vim even more.

**Comment by tommyjcarpenter** [comment]
Hey all, coming in as a spectator here... this discussion hasn't been updated in 5 years. What is the current state of things? Is the jedi integration into YCM complete to the point where jedi-vim is "deprecated", or is that not true and jedi-vim still has features for python that YCM does not have? Asking as someone with both plugins currently enabled, and suffering issues, in their .vimrc!

**Comment by dbrgn** [comment]
I've been using YCM with Jedi for years now, it's working great :slightly_smiling_face: On the other hand I only use completion, goto-definition and show-docs. I think the only other feature that jedi-vim supports and YCM does't(?) is renaming, right?

In any case, I much prefer YCM's speed and complete-as-you-type over an explicit completion trigger.

**Comment by davidhalter** [comment]
I think there are still a few differences. jedi-vim does a few additional things like call signatures, `:Pyimport`, renaming, a special kind of import completion, probably more configuration options, etc. 

There's also deoplete-jedi if you're looking for async completions. This is what feels faster with YCM. @blueyed might know a bit more about the differences than me. 

YCM itself is not faster, it's just asynchronous. As long as you wrap Jedi, Jedi will be the botteneck. jedi-vim itself is a very small wrapper around Jedi.

https://github.com/zchee/deoplete-jedi

**Comment by tommyjcarpenter** [comment]
I came to this issue because I have been having very bizarre issues on my Mac after using Vim. For example, my main OS X copy paste getting obliterated and pasting random python code whenever I hit command-V! Sometimes the python code contains the word "jedi". So I started investigating whether I possibly have something bad going on in my .vimrc and started commenting out certain plugins and researching whether some of my plugins might "overlap", and sure enough I came here. And I seem to have solved the clipboard problem and so I believe some bad combination of plugins was causing the issue. I would have to take a video to see show bizarre the paste becomes after using Vim, sometimes killing `pboard` was enough, and sometimes a reboot was required. 

So that aside, my goal isn't to stand behind one tool or the other and say it's better, it's only to have multiple language support (python, js, erlang, c++, etc) in a set of non-overlapping orthogonal plugins. If the simplest solution to that problem is to just use YCM that's my vote. If it's to use jedi-vim for python and other plugins for other languages , that's great too. So I was just looking for guidance. For now I will roll with YCM but I was open to suggestions in using jedi-vim + other plugins for other languages.

**Comment by blueyed** [comment]
@tommyjcarpenter 
The clipboard issue sounds like some plugin is using the clipboard register for some handling, which is likely not jedi-vim.  Please consider creating separate issue(s) for the relevant plugins to get this fixed.

**Comment by tommyjcarpenter** [comment]
@blueyed Empirically, commenting out jedi-vim has solved the issue. This is not a thorough analysis because I have not slowly investigated this issue by turning on/off plugins one by one to find the exact culprit. My current hunch is that jedi-vim alone is not to blame, but rather some unfortunate combination of non-orthognal plugins causing an unexpected issue. Since sticking to just YCM I have not seen the issue, yet.

**Comment by davidhalter** [comment]
I think that it's save to say that we have in some ways worked together. Jedi is used within YCM and jedi-vim has always been a side-project.

The times have been changing and language servers have emerged as the new market leader. I still think that language servers have a bit too much overhead (both in complexity and resources), but that's probably not going to stop people from using them.

So I'm glad YCM, jedi and jedi-vim have become what they are now. Cheers to a few more years!
