### ISSUE TITLE
Cannot choose method/class/etc.

### ISSUE THREAD

**Issue by Relrin** [davidhalter/jedi-vim#162]
I'm trying to install jedi-vim with Vundle plugin, and typing this "example":

   import math
   math.

fter dot i get popup with autocomplete. Really not bad, but, i cant choose function/method/class/etc. what i want (arrows somehow doesn't worked, when show popup with autocomplete and preview of first function/method/class/etc. which automatically selected)

At my .vimrc file:

   let g:jedi#popup_select_first = 0
   let g:jedi#goto_command = "<leader>g"
   let g:jedi#get_definition_command = "<leader>d"
   let g:jedi#rename_command = "<leader>r"
   let g:jedi#related_names_command = "<leader>n"
   let g:jedi#autocompletion_command = "<C-Space>"

P.S. Maybe incompatible with some plugin, which installed also by Vundle: NERDTree, NERDCommenter, TagBar, minibufexpl.vim, FixedTaskList.vim, conque-term, vim-snippets, vim-snipmate, vim-addon-mw-utils, tlib_vim, git-vim, vim-gitgutter, vim-airline, python-mode?

**Comment by kreedz** [comment]
I have the same problem.
![animation](https://cloud.githubusercontent.com/assets/2128965/6574619/974f71fc-c748-11e4-8597-9430d6c79d4e.gif)

As you can see there [No Name] buffer appears when you reach third frame and almost whole selection window disappears (a small piece remains on the statusline). But i'm not sure that it is the "buffer", because :ls command don't shows this  "buffer".

And I founded the cause.
In my .vimrc, the following command:
let g:airline#extensions#tabline#enabled = 1
does this:
'Automatically displays all buffers when there's only one tab open.'
If you disable this then the problem disappears. But i don't want to disable this command. How i can avoid this?
I do not know whose exactly it is a problem (jedi or airline).

**Comment by davidhalter** [comment]
Thanks so much for the comment!
