### ISSUE TITLE
Autocomplete for two python paths

### ISSUE THREAD

**Issue by pratz** [davidhalter/jedi-vim#195]
My project dir structure
1) /sdk/python/src/code/  ## project code
2) /sdk/python/tests/utest/code/  ## unittest code
Here 'code' and 'utest' are python packages

So, my .bashrc looks like this
PYTHONPATH="/sdk/python/src/"  ## project source code path
PYTHONPATH="/sdk/python/tests/:$PYTHONPATH"  ## project unit test path
export PYTHONPATH

Now, I open up my editor (vim) and do
from utest.code. ## auto complete lists all the packages/modules from 'project source code path' , where as it should list the packages/modules from 'project unit test path'.

Any help is appreciated.

**Comment by davidhalter** [comment]
Nothing has happened here. I will just close for now. Let me know if there are updates here.

**Comment by memeplex** [comment]
@davidhalter I'm having a similar problem, here is a step by step procedure to reproduce the problem:

```
mkdir /tmp/proj
cd /tmp/proj
mkdir pkg
touch pkg/__init__.py
touch pkg/mod.py
mkdir tests
touch tests/__init__.py
mkdir tests/pkg
touch tests/pkg/__init__.py
touch tests/pkg/test_mod.py
export PYTHONPATH=/tmp/proj:$PYTHONPATH
vim tests/pkg/test_mod.py
```

Now try to autocomplete `import pkg.`, jedi will suggest only `test_mod`, which is wrong given the `PYTHONPATH`, and won't suggest `mod`, which is also wrong.

Now, if you edit `pkg/mod.py` instead, `import pkg.` will correctly suggest `mod`. It is as if the file being edited is influencing jedi's notion of the python path.

**Comment by memeplex** [comment]
I wonder if this has to do with relative imports, I'm using python 3 since many years now so I'm now really well versed in relative imports anymore.

**Comment by memeplex** [comment]
I decided to open a new issue (#702).

**Comment by heshamsafi** [comment]
I also have the same problem ... I think jedi stops searching the sys.path as soon as it finds a match.
and in my projects java style module names are being used for some reason so it is like com.whatever.whatever
and I only get completion for the first package in my sys.path. I am sad.
I am surprised that this is an edge case, I would have imagined tons of people are using the same stupid module naming convention.
if I miraculously find time I will dive into the jedi library and try to fix it somehow. in the mean time I will just be using ctags.

**Comment by davidhalter** [comment]
@heshamsafi Jedi tries to search for a project directory. There needs to be a `setup.py` or a `requirements.txt`. This directory will be part of the `sys.path` and used with priority.

The effect you're seeing is just a fallback, if the normal import mechanism is not working.

**Comment by heshamsafi** [comment]
I am sorry I didn't understand that. I kinda feel like you have the solution to my problem so please take me to the light. :)
I already have all the root directories of all the dependencies crammed into the sys.path of the python process that jedi runs on by setting "let g:ycm_python_binary_path = /path/to/somescript.sh" in .vimrc
somescript.sh will have in it
autogenerated PYTHONPATH var from my project via a script and then just 
python "$@"
which causes jedi to know where everything is with our internal build system structure, except that it can't figure out the package names with overlapping prefix with another package.

**Comment by heshamsafi** [comment]
how can setup.py or requirements.txt help with that ? can you please elaborate ?

**Comment by davidhalter** [comment]
Look I feel like you are over-complicating things. I'm not sure I have a good solution for you. There's only so much Jedi can do. I haven't really had people complain since 0.13, because it actually solved a lot of the issues people had before with this.

I feel like you could probably move to a more typical Python approach of working with it. Maybe that's not true and you need the complexity. However I feel like the issue is somewhere in there.

Otherwise you could just try to reproduce your issue as a breaking test in the Jedi repository. We're always happy if it really doesn't work. However IMO the current version is pretty bullet proof.

**Comment by heshamsafi** [comment]
Thanks for trying to help.
sadly a more typical python approach is not an option where I work where they force us to use this unpopular build system which mangles everything into an undecipherable mess.
what I will do is that I will try to understand why this happens and if I think it is something Jedi should handle I will submit a PR, because this setup that I have is the closest I can get to code completion and navigation at work.
