### ISSUE TITLE
Add an option to disable key bindings

### ISSUE THREAD

**Issue by Julian** [davidhalter/jedi-vim#213]
Hey,

Would you be willing to add an option to disable binding keys? (Apologies if it exists already, I only see `g:jedi#auto_initialization = 0` but that disables more than just mappings).

I know you can remap each key to make it use a different key, but that means that users have to go look up each map and pick some other key, even if they don't care about it (i.e., I just want Jedi to not quash my mappings, I don't really care about all the functionality it's mapping).

Another alternative (or something to consider) based on the above would be to not map keys if they're already mapped to something else.

**Comment by sloria** [comment]
Sorry to post on an old issue, but I still think this would be a useful feature. I, too, was looking for an option to disable setting of the default keymappings (without turning off other initialization steps, e.g. omnifunc).

That said, I respect that you want to keep jedi-vim's configuration/API small.

**Comment by blueyed** [comment]
We might at least use `:map-<unique>`, which would display an error if a mapping is used already.
Or to be more friendly: check this ourselves and provide helpful instructions.

I also think that there are a lot of settings already.
Best practice would be to use `<Plug>` mappings, instead of settings for the left-hand-side of the map.
We could then check if a map to something is provided already (which means the user has defined it manually).

But it would need to handle the old settings for B/C and therefore it's probably not worth it.

**Comment by davidhalter** [comment]
I personally still think that the current way is ok. I would be willing to use `unique`, if that helps. But I don't really want to add new settings.

**Comment by Julian** [comment]
`unique` is the wrong direction (would be worse) IMO. It's my mapping I want, `jedi` shouldn't cause errors on startup :).

**Comment by Julian** [comment]
Just as another example of why the current solution isn't nice to users (well, really to me, I can't speak for anyone else), a recent commit broke my leader mappings once again, because `g:goto_command` was added, which I wasn't overriding.

**Comment by dbrodie** [comment]
I agree with @Julian, I would like a feature like this as well, especially since I don't use jedi-vim as much by itself rather than integrate it into existing completion frameworks (such as deoplete, neocomplete) so that it is consistent with other languages I program in.

I think the best solution is to use the <Plug> mapping and have a setting to disable the mapping, or something equivalent.

**Comment by blueyed** [comment]
You're welcome to provide a PR.

> I don't use jedi-vim as much by itself rather than integrate it into existing completion frameworks (such as deoplete, neocomplete) 

But then you still use the goto-mappings etc, no?  deoplete-jedi ships its own jedi, and does not require jedi-vim.

I could imagine having one setting to not define any automatic mappings.

But me nor David won't do it, so you need to contribute (and support it).

**Comment by kadaliao** [comment]
Hi there, I'm a new commer here.   

It has been 6 years that I got the honor to add 3 lines of code to make this contribution?

😃😃😃

**Comment by blueyed** [comment]
> `unique` is the wrong direction (would be worse) IMO. It's my mapping I want, `jedi` shouldn't cause errors on startup :).

We would/could hide errors from there, of course - and/or check if a map exists already.
But in general I think having an explicit setting for this makes things easier.  (#943)
