### ISSUE TITLE
jedi-vim automatically overrides tabstop, shiftwidth and expandtab

### ISSUE THREAD

**Issue by pdvyas** [davidhalter/jedi-vim#237]
On 0.5.0 version, behaviour is as intended but jedi-vim 0.7.0 overrides tabstop and sets expandtab (even if vimrc has noexpandtab). 

tried,
`autocmd FileType python setlocal noexpandtab tabstop=4 shiftwidth=4` 

but doesn't work for the first file (works for the files opened subsequently).

vim version 7.4.86 and I use vundle

**Comment by emdete** [comment]
since i installed jedi-vim i have exaclty that behaviour as well. 

instead of the lines above these work:

```
autocmd BufRead,BufNewFile * set softtabstop=0
autocmd BufRead,BufNewFile * set noexpandtab
```

in fact the settings origin seems to be:

```
/usr/share/vim/vim80/ftplugin/python.vim:97
```

which is activated on `g:python_recommended_style != 0`. so i added a line

```
let g:python_recommended_style = 0
```

to my .vimrc (after the plugin infect()) which does the job as well. 

the variable is set to none 0 by default and used when filetype python is activated. this doesnt seem to be the default but is activated by jedi-vim.
