### ISSUE TITLE
Declaring a class instance + method call between import and another statement breaks undo

### ISSUE THREAD

**Issue by waldeinburg** [davidhalter/jedi-vim#285]
The undo queue breaks if inserting a class instance declaration and a method call between the import statement and something else, including whitespace.

I'm pretty sure the following is a minimal example and I have also tried it without jedi-vim installed:
1) Begin editing a new python file in vim.
2) Write the following and exit input mode (two newlines after the import):

```python
from collections import deque


```

3) Enter input mode again and insert a declaration and a method call:

```python
from collections import deque
d = deque()
d.clear()

```

4) Exit input mode and press 'u'. Now the buffer displays:

```python
from collections import deque

d.clear()

```

5) Press 'u' again. The buffer will be empty as if the 'd.clear()' was entered at step 2.
If you save and exit after step 2) then step 5) will give the message: "Already at oldest change"

**Comment by davidhalter** [comment]
After playing with it again, I don't think that we can fix it, so I'm closing. It's a feature that comes with call signatures. The alternatives are:

    let g:jedi#show_call_signatures = "2"

fixes this issue, because there's no modification of the buffer anymore. But then the call signatures are in a different position (which is probably ok for most people). 


    let g:jedi#show_call_signatures = "0"

just disables call signatures altogether.
