### ISSUE TITLE
no cache updates

### ISSUE THREAD

**Issue by montefra** [davidhalter/jedi-vim#290]
I'm working on a very complex code, where each file has order or 10 or more `from XX import Whatever` and some absolute import. 
Some of the import are from the same package, some from an other huge package. As now the code is hosted in an afs directory.

Example:

```
[... lots of import ...]
from my.huge.package import Persistent

[... some code ...]

parameter = Persistent("a string", some_parameter, 0)
```

The problem is that every time I enter <insert> mode within the parenthesis, vim hangs form few minutes doing something. If I try to get the documentation of `Persistent`, vim hangs again. I've also noticed that the jedi cache (under `~/.cache/jedi/cpython-27`) is not updated.

To test if there was anything broken with the cache, so I removed it. If I try `import os` and use `os.` everything works as expected and the new cache is created. But again the cache is untouched when I try to edit `Persistent`. 

I've a copy of the code in my machine, that doesn't know anything about `my.huge.package`. For now I'll use it so I can work without too much pain. 

If there is no better solution, is there a way to disable jedi on some module? Something like the opposite of `jedi.preload_module`?

Thanks for Jedi!

**Comment by davidhalter** [comment]
Still happening? Did it get better? Please update to the latest Jedi dev branch before checking. I have hopes that some things have sped up quite a bit.

**Comment by montefra** [comment]
@davidhalter yes, I still see the same problem. 

To deal with plugins I use junegunn/vim-plug and I've updated my plugins ~ an hour ago. Now I'm using:
davidhalter/jedi-vim@d82df60392293b24b957c4e7a1cbf4c4053610ad
davidhalter/jedi@7b402d7bbe0e07554f1f97ee3558167961a99b5a

**Comment by davidhalter** [comment]
No, you have to checkout the latest Jedi dev branch. The commit you're currently using is quite old.

**Comment by montefra** [comment]
I've checked out the dev branch and I should be using davidhalter/jedi@4bb41b609648767b7e489a457bcd25b84d43067a but I don't see a speed improvement.

Vim tells me 
```
:python import jedi; print(jedi.__version__)
0.9.0
```

It could well be that it's fault of the afs file system: sometimes it hangs as it caches new directories and here there are al lot of subdirectories and files

**Comment by davidhalter** [comment]
And with the current Jedi dev branch?

**Comment by postcapital** [comment]
I had to downgrade my jedi library from 0.11.0 to 0.9.0 as caching was not working with jedi 0.11.0.  Is this issue actually anything to do with jed-vim and what version of jedi does it support?

**Comment by davidhalter** [comment]
This issue was created years ago, well before 0.10.0. Can you describe your issue a bit better? I really have no idea what your problem is.

**Comment by postcapital** [comment]
Thanks David because this is my only vim plugin I use and I really appreciate it and highly recommend it to other python developers and vim fans, writing a vim plugin looks incredibly complicated!  My story is that I recently remade my virtualenv which is in my path and noticed the newer version of this plugin was hanging badly searching new libraries.  I deleted my cache in ~/.cache/jedi/cpython-27 and noticed the new version of jedi 0.11.0 had made an empty cache in ~/.cache/jedi/CPython-27-30  and wasn't updating.  I'm not the only one who has lost jedi cache which is what I think would happen if I installed jedi-vim from scratch without downgrading jedi.  I've just re-checked this again and the master branch of jedi-vim does not make cache for me with jedi 0.11.0 but does with 0.10.0.  I just don't want others to have the same issue.

**Comment by davidhalter** [comment]
@postcapital With the transition to parso for the parser this path might have changed. Do you see anything under `~/.cache/parso/`?

**Comment by blueyed** [comment]
jedi-vim is not using parso yet.
@postcapital 
Have you install Jedi manually, or do you use the submodule from jedi-vim?

**Comment by postcapital** [comment]
yes there's now a big cache in ~/.cache/parso/CPython-27-30/ which explains what happened with jedi 1.0.11. I have always installed jedi manually as the submodule didn't install itself   How do I install the submodule properly if pulling from git and is it the correct version if parso isn't working yet?  Thanks for your help.

**Comment by blueyed** [comment]
jedi-vim uses a submodule by default from its subdirectory.
So you are saying that you use jedi-vim, but have not cloned it with e.g. `--recursive` and since that failed then you installed jedi manually?

jedi-vim has not upgraded to 1.0.11 yet.
What you are seeing currently is what you would see then I suppose.

I think it is good to have Jedi installed separately, but usually should not be necessary.

**Comment by blueyed** [comment]
And for the issue itself: you have some cache, but might just be hitten by slowness etc.
You should really create a new issue by now, likely in Jedi's repo.

**Comment by montefra** [comment]
@davidhalter : thanks for closing it. I forgot about it and I haven't worked with the packages described in the orginal report in a long time.

**Comment by postcapital** [comment]
Hi again Dave,
I'm liking this plugin more since not using any other editors.
Does jedi-vim now support parso? It was making the parso cache but no good
at reusing it but will do some more testing before making a new issue.
James

**Comment by davidhalter** [comment]
Jedi 0.11.0 is using parso, however jedi-vim is still on jedi 0.10.2. #746 is the attempt to update to 0.11.0.
