### ISSUE TITLE
Rename issue (test case)

### ISSUE THREAD

**Issue by c0ffeeartc** [davidhalter/jedi-vim#301]
Trying to rename 'a' in this example few times,  renames 'b' instead, reverts names of 'a' and 'b'

```
def main():
    b = 6
    a = b
    print (a)
```

<code> python import sys; print sys.version </code> -> <code>
    2.7.6 (default, Mar 22 2014, 23:03:41)  
    [GCC 4.8.2] </code>
<code>   :python import sys; print(sys.version_info) </code> -> <code>    sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0) </code>

**Comment by blueyed** [comment]
Still an issue.

The bad thing here is that trying to rename `a` in the `print()` will revert it (doing 0 replaces).
That should not happen - at least this occurrence should get replaces probably?!

(It's caused by how Jedi-vim does it: it will undo the change in Vim, and then call jedi (which fails)).

**Comment by davidhalter** [comment]
Just a side note: Refactoring will be coming to Jedi, so that might also fix a lot of renaming problems we have.

**Comment by davidhalter** [comment]
This doesn't seem to be an issue anymore with Jedi 0.11.0.
