### ISSUE TITLE
Cannot go to definition for classmethods

### ISSUE THREAD

**Issue by UkuLoskit** [davidhalter/jedi-vim#306]
Example: 
```
class Clazz(object):
    @classmethod
    def method1(cls):
        print "Hello World!"

Clazz.method1()
```
If the cursor is placed on method1 goto_definition() does not seem to work.

**Comment by blueyed** [comment]
As for jedi-vim the "goto" mode falls back to `goto_assignments` since a while, so it works there flawlessly.

I wonder if this is still planned to be addressed in Jedi?!
Would then  `goto_definitions` go to the decorated function already?
Should this issue be moved to the Jedi repo? (if there is none already about this)

**Comment by davidhalter** [comment]
Hmm, I think we can safely close this one, because it' not totally false that we end up within the descriptor when we use `goto_definitions`. `goto_definitions` has very special use cases and should really only be used to get type (or rather value) inference information. It's something that I would not encourage people to use anymore.

While the return value `_method` is something strange to receive, I think that it's just not totally bad either (it's still a function and people shouldn't use goto_definitions). It's just not worth putting a lot of effort into this on the side of Jedi. It's a flaw, but a minor one that most people shouldn't even see.

I think we should document that using `goto_definitions` should not be used for most things.

**Comment by blueyed** [comment]
> I think we should document that using goto_definitions should not be used for most things.

Will you do it right away, or should we create an issue for it?

**Comment by davidhalter** [comment]
Create an issue :) Sorry, too many things around my head at the moment...
