### ISSUE TITLE
Is it possible to not lose focus when using the documentation popup?

### ISSUE THREAD

**Issue by joehanchoi** [davidhalter/jedi-vim#357]
Hey — love the plugin. Only issue (and probably more of a request at that) is that losing pane focus to the documentation pane is a slight hassle for my workflow — usually only need to peek at the docstring before moving on.

I was wondering if the `jedi#show_documentation()` could be called without losing focus in the active pane. Thanks!

**Comment by davidhalter** [comment]
Hmm good question. I guess that would be possible, but then again, scrolling will be difficult in the docs windows, which is often the case for longer docstrings.

So I guess this won't happen, not even as an option, because the interest for something like that is low and there's always the maintenance cost.
