### ISSUE TITLE
vim (jedi-vim) closes / quits slowly

### ISSUE THREAD

**Issue by mayuroks** [davidhalter/jedi-vim#375]
In vim, After editing python file, when I type ```:wq```  I have to wait for 3 secs and then vim quits. Is there any way to make it faster ?

**Comment by davidhalter** [comment]
Does that only happen with jedi-vim?

I don't think that this is really a jedi-vim isue, since jedi-vim does absolutely nothing when closing VIM. jedi-vim has a low overhead in any case and might slow down when you hit `.` in insert mode or try to use completion. But otherwise I don't see any scenarios of it slowing down VIM.

**Comment by mayuroks** [comment]
Thanks a lot. I just found that it wasnt jedi-vim. It was syntastic that was causing the issue. If you have any tips on speeding syntastic I would appreciate it. I am closing this issue.

**Comment by davidhalter** [comment]
Sorry I guess I don't have any. I'm an avid user of syntastic and love it. But I also almost never close VIM sessions, so I don't care as much.
