### ISSUE TITLE
Auto-increase cmdheight when with long sigs and show_call_signatures=2

### ISSUE THREAD

**Issue by fvisin** [davidhalter/jedi-vim#474]
When `jedi#show_call_signatures` is set to 2 a "Press ENTER or type command to continue" prompt appears every time a signature should be shown, unless `cmdheight` is set to 2. 

This workaround solves the problem by using a 2-lines command line, which is a waste of space and very ugly IMHO. I was wondering if it might be possible to automatically increase `cmdheight` before showing the signature, and decrease it back to the original value afterwards.

**Comment by blueyed** [comment]
> a "Press ENTER or type command to continue" prompt appears every time a signature should be shown

I've never seen this.  Is it because the signature is too long?
Otherwise there seems to be a bug with your setup.
Please post your output of `:version`, and make sure to use the latest jedi-vim.

**Comment by fvisin** [comment]
Yes, the problem arises when the signature is too long to be displayed. The best would be to temporary increase cmdheight of an amount that depends on the signature length. I am not an expert though, so I don't know if it is feasible.

**Comment by davidhalter** [comment]
cc @wilywampa, because he originally implemented this.

**Comment by wilywampa** [comment]
I'd also like to know your version and settings for `ruler`, `rulerformat`, `shortmess`, `showcmd`

Assuming you do have `ruler` set, this branch might be an improvement: https://github.com/wilywampa/jedi-vim/tree/callsig_columns

There are a couple complications that make:
- There is no way to check how much space vim is using in the command line for `showmode`, `ruler`, and `showcmd`
- Changing those settings in insert mode from Python corrupts the undo history so that's not acceptable

The code checks the length of the signature before displaying it and bails out if it thinks it will be too long (https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L401).  The problem may be that I pulled the value of 12 columns that it uses to account for `ruler` and `showcmd` out of nowhere but I never have those settings enabled so I haven't run into it. I just actually measured how much space is used (assuming unset `rulerformat`) and it's 27 characters for both `showcmd` and `ruler` 17 characters for just `ruler`, and 10 for just `showcmd`.

I spent some time adjusting my tmux split size column-by-column with the different combinations of settings and found accounting for an additional 18 columns if `ruler` is set works pretty well, i.e. it refuses the draw the signature once the window gets even a column too narrow instead of giving the prompts like before. I made that change in the branch above.

**Comment by blueyed** [comment]
> it refuses to draw the signature

Couldn't it be also cropped at the end, using "…"?

**Comment by wilywampa** [comment]
Using ellipses is a really good idea. I'm working on that.

**Comment by fvisin** [comment]
Sorry the time it took me to answer. Here are the information you asked me:
```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +cmdline_info    +emacs_tags      -hangul_input    +menu            +mouse_xterm     -python3         +syntax          +virtualedit     +xsmp_interact
+arabic          +comments        +eval            +iconv           +mksession       +multi_byte      +quickfix        +tag_binary      +visual          +xterm_clipboard
+autocmd         +conceal         +ex_extra        +insert_expand   +modify_fname    +multi_lang      +reltime         +tag_old_static  +visualextra     -xterm_save
+balloon_eval    +cryptv          +extra_search    +jumplist        +mouse           -mzscheme        +rightleft       -tag_any_white   +viminfo         +xpm
+browse          +cscope          +farsi           +keymap          +mouseshape      +netbeans_intg   +ruby            +tcl             +vreplace
++builtin_terms  +cursorbind      +file_in_path    +langmap         +mouse_dec       +path_extra      +scrollbind      +terminfo        +wildignore
+byte_offset     +cursorshape     +find_in_path    +libcall         +mouse_gpm       +perl            +signs           +termresponse    +wildmenu
+cindent         +dialog_con_gui  +float           +linebreak       -mouse_jsbterm   +persistent_undo +smartindent     +textobjects     +windows
+clientserver    +diff            +folding         +lispindent      +mouse_netterm   +postscript      -sniff           +title           +writebackup
+clipboard       +digraphs        -footer          +listcmds        +mouse_sgr       +printer         +startuptime     +toolbar         +X11
+cmdline_compl   +dnd             +fork()          +localmap        -mouse_sysmouse  +profile         +statusline      +user_commands   -xfontset
+cmdline_hist    -ebcdic          +gettext         +lua             +mouse_urxvt     +python          -sun_workshop    +vertsplit       +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/
include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux
-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz   -pthread -DORBIT2=1 -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/incl
ude/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/i
nclude/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linu
x-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-ac
tivation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/x8
6_64-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/libpng12     -g -O2 -fstack-protector --param=ssp-
buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1

Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.
0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2
-lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.
0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE
 -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/pe
rl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bs
ymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```

I set `ruler` in my .vimrc, while `rulerformat`, `shortmess`, `showcmd` are at their default value.

I agree that ellipsis seems to be the best solution here. You could keep the signature centered on the current value, adding ellipsis at the beginning and/or at the end of the signature when needed. 
E.g.:
```python
def my_funct(arg1, arg2, arg3, arg4, arg5, arg6, arg7):
    pass
```
You could show:
* `my_funct(arg1, arg2, arg3, …)` when the cursor is on arg1;
* `…, arg3, arg4, arg5, arg6, …)` when the cursor is on arg5 
and so on.

An alternative could be:
* `my_funct(arg1, arg2, arg3, …)` when the cursor is on arg1;
* `my_funct(…, arg4, arg5, arg6, …)` when the cursor is on arg5 
and so on.

**Comment by wilywampa** [comment]
Thanks for the version/setting information.

What I implemented is pretty close to your suggestion except instead of handling each argument independently, I split the arguments into before, current, and after. If there's not room for all of them, first I change all the before to `...`, then I change the after to `...`, then finally I change all of it to `...`.

![callsigs](https://cloud.githubusercontent.com/assets/4472522/10548948/f6c8e7d8-73f2-11e5-8350-417757f03bf9.gif)

The commit with that change: https://github.com/wilywampa/jedi-vim/commit/3b18498c037dcff15868223ab83bba48ecf08042

**Comment by fvisin** [comment]
Sounds great! I will check it out as soon as possible.

**Comment by blueyed** [comment]
Sounds awesome indeed.  Can you please create a PR for it?

**Comment by davidhalter** [comment]
@wilywampa 

> What I implemented is pretty close to your suggestion except instead of handling each argument independently, I split the arguments into before, current, and after.

Very nice. I might be interested to integrate that within Jedi.
