### ISSUE TITLE
Why jedi-vim is too slow compared with ptpython

### ISSUE THREAD

**Issue by Congee** [davidhalter/jedi-vim#498]
I know already there is a relevant issue #163 , but watch the gif at first.
![ptpython](http://45.32.22.151:8000/output.gif)

See? ptpython is blazingly fast the first time it completes numpy, which is considered a large module.
I think the reasons lie behind:
1. ptpython uses a global cache
2. VimL is slow compared with Python
3. ptpython completes at every stroke, making it fast with the next eval.

It doesn't matter for who write daily small scripts and for who edits all the time without leaving vim. How about for those who write small scientific computation scripts?
Any suggestions?

**Comment by davidhalter** [comment]
Hehe. It's fun how you try to argue why it's slow, but essentially you have no idea, because it's a black box :).

You're arguing that ptpython is faster when it comes to completion. This is obviously kind of wrong, because both jedi-vim and ptpython are using Jedi underneath.

The difference is a simple one: ptpython uses Jedi within a shell. Jedi can therefore profit from Python's introspection capabilities (which are obviously fast, e.g. `dir(...)`), whereas jedi-vim works purely with text (code), which means: No introspection. Theoretically we could execute that code, but that is just a big security issue - think about just executing `os.system('rm -rf /')`. That's not what you want. Therefore more analysis and therefore CPU time is needed. It's simply not possible to be as fast as ptpython.

However, I still like the fact that you compared the speed of two different Jedi usages :-)

BTW your .GIF is not working.

**Comment by Congee** [comment]
Well, that's embarrssing. I've never thought about security. It couldn't be better if there is a way to improve the speed. Thanks for your detailed explanations of instrospection and security. :D

**Comment by gerryqd** [comment]
Both ptpython and jedi.vim work slow on my environment (win764, cygwin), 
On the same machine, the windows version works well.

For the slow case, when it is ptpython, after I input the first letter after the "import " statement, it will takes about 20 seconds to response.

When it was the "jedi.vim", "import" statement works well, but the auto completion will be very slow, after I type the "." after the package name, it will also takes about 20 seconds to get response.

**Comment by davidhalter** [comment]
We have had a lot of reports that Jedi is slow on cygwin. I won't fix it, because I don't even run windows. However it's something that probably has to do with cygwin itself.
