### ISSUE TITLE
Can't rename function parameters

### ISSUE THREAD

**Issue by NoAnyLove** [davidhalter/jedi-vim#502]
Rename fails on renaming function parameters. For example, if I have code below,

```python
def dummy(ss):
    print ss
```

When I move the cursor on the `ss` of `dummy(ss)` and rename it, the `ss` will disappear, and prompts `Jedi did 0 renames!`, the code becomes:

```python
def dummy():
    print ss
```

However, if I put the cursor on the `ss` of `print(ss)` and rename it, it will successully rename, but I need input one more space before input the new name, because the rename process will delete `ss` and the space before it. And if I don't input one more space, i will become (assume I rename `ss` to `cc`),

```python
def dummy(printcc):
    print printcc
```

**Comment by mozbugbox** [comment]
The `ss` disappeared because the undo tree got messed up when returning from the insert mode.
When getting out of insert mode, we do 2 undo to restore the origin text.

However when renaming a parameter in a function definition, the function signature auto-completion/hinter might kicked in and insert the function signature somewhere in the buffer. Now 2 undo is not enough if function signature hint was inserted into the buffer. 2 undo only restore to where we just deleted the to be renamed parameter, hence it disappeared.

A patch was supplied to fix it.

However, it seems rename() cannot rename the following case:
```
def func(a, b):
   a = 12
   c = a
   if True:
       c = b
```
Renaming `a` or `c` will only rename itself, but not the 2nd assignment statement.

Because `usage.usage()` use `jedi.evaluator.Evaluator.goto()` to test if the given names are defined in the same position. The `goto()` call returns itself as definition position for assignment statement. So the new assignment are dropped as out of scope.

I guess variable scopes should be tested instead of testing if the variables are defined at the same position for rename().

**Comment by blueyed** [comment]
@mozbugbox 
Thanks!

I guess there should be a new issue for your new findings?!

**Comment by davidhalter** [comment]
Thanks for researching this thoroughly @mozbugbox! This has been an issue forever. And thanks for providing a fix @blueyed!! I'm really busy at the moment and have trouble to find time.

**Comment by blueyed** [comment]
@davidhalter
The fix was from @mozbugbox after all.

Take care! One intention of the fix for the better error message was indeed to give you/us some more room to breath from hard to triage issues, and for you to spend your time on Jedi itself.. :)
