### ISSUE TITLE
Autocompletion for virtual environment modules working in Python 2 but not in Python 3

### ISSUE THREAD

**Issue by anderslundstedt** [davidhalter/jedi-vim#503]
With vim compiled with +python -python3 and with a Python 2 virtual environment activated, completion works for everything.

With vim compiled with -python +python3 and with a Python 3.5 virtual environment (created with the pyvenv tool) completion works for everything except for modules installed in the virtual environment.

**Comment by tony** [comment]
There is no Python 3 + Virtualenv support on vim as of December 20, 2015.

I was going to do a project in pure Python 3.5, however came to a surprise when other packages relied upon for handling virtualenv didn't work with python 3.x virtualenvs. To see why, see the tickets linked to below.

> With vim compiled with -python +python3 and with a Python 3.5 virtual environment (created with the pyvenv tool) completion works for everything except for modules installed in the virtual environment.

Are you sure the virtualenv is really activated in python 3? Are you use a separate plugin for your virtualenv?

With -python +python3, what you're experiencing may be because virtualenv isn't activating and you're only getting completion for the standard lib packages.

On neovim, it's possible to simulate +python and +python3 simultaneously. I've had working jedi completion, but like you, only for standard library packages.

Related issues, #467, https://github.com/jmcantrell/vim-virtualenv/issues/45, https://github.com/klen/python-mode/issues/406

Related reddit thread: https://www.reddit.com/r/vim/comments/2j0fxc/python_3_completion_vim_plugins/

**Comment by williamsmj** [comment]
Any news on this? Looks like there's been some movement on some of the issues @tony referenced since his previous comment. Would be great to get jedi-vim working with python3!

**Comment by blueyed** [comment]
It certainly is possible, and you might only be missing the virtualenv activation.
Apart from that, Neovim is more flexible and you can use 2 + 3 at the same time.
I also recoomend pyenv + pyenv-virtualenv.

**Comment by williamsmj** [comment]
neovim (and pip install neovim in the relevant virtualenv) worked for me. Thanks!

Could you say more about how to make it work in vanilla vim? Do I need to do something more than activate the virtualenv in the shell from which I run `vim file.py`?

I agree pyenv and pyenv-virtualenv are great, but I don't see how they are relevant to this problem. Am I missing something?

**Comment by davidhalter** [comment]
Virtualenv support is still broken in Jedi. I plan to tackle it soon. (This issue: https://github.com/davidhalter/jedi/issues/385). Because until Jedi really supports it, it's just not a clean solution.

**Comment by williamsmj** [comment]
Thanks. In this meantime, for anyone reading this: I got things working using the following ugly hack: I dug up a copy of python2 virtualenv's `activate_this.py` and stuck it somewhere convenient (in my case I put it in `~/.vim`). I then added to the end of my `~/.vimrc`.
```
" Add the virtualenv's site-packages to vim path
py3 << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    # activator = os.path.join(project_base_dir, 'bin/activate_this.py')
    activator = os.path.join(os.environ['HOME'], '.vim/activate_this.py')
    with open(activator) as f:
        exec(f.read(), {'__file__': activator})
EOF
```
This works in the sense that vim's understanding of `sys.path` includes the active virtualenv's site-packages, and expansion, documentation, goto defintion etc. all work. But seems particularly ugly. It only works for python3. I have to activate the appropriate virtual environment before launching vim. I need to know what I'm working on before I open vim, and I can only work on one vim session per project.

**Comment by blueyed** [comment]
@williamsmj 
Check out https://github.com/jmcantrell/vim-virtualenv/.

**Comment by davidhalter** [comment]
Will be fixed with https://github.com/davidhalter/jedi/issues/385
