### ISSUE TITLE
Rename ignores variable assignment in the same scope

### ISSUE THREAD

**Issue by mozbugbox** [davidhalter/jedi-vim#552]
It seems rename() cannot rename the following case:

``` python
def func(a, b):
   a = 12
   c = a
   if True:
       c = b
```

Renaming a or c will only rename itself, but not the 2nd assignment statement.

Because usage.usage() use jedi.evaluator.Evaluator.goto() to test if the given names are defined in the same position. The goto() call returns itself as definition position for assignment statement. So the new assignment are dropped as out of scope.

I guess variable scopes should be tested instead of testing if the variables are defined at the same position for rename().

**Comment by davidhalter** [comment]
Renaming works a lot better now.

In this case, a renames without issues, c renames only one statement. This is intentional, though.

If you replace the `True` with pretty much any value that is not always true, it will rename both names. The reason for this is that:

```
c = 1
c = 2
```

Are considered independent variables and are not renamed, because of stuff like this:
```
error = ...
if error:
    ...

error = ...
```

In this case a variable is reused and is completely independent. If you don't like this, please open a new issue in Jedi and we'll discuss it.

**Comment by davidhalter** [comment]
Decided that I didn't like that decision and now your cases should all work.
