### ISSUE TITLE
Get completions for modules that aren't imported yet

### ISSUE THREAD

**Issue by infokiller** [davidhalter/jedi-vim#579]
Even support for only standard library modules would be very useful. 
Is that possible?

Ideally, I'll also be able to configure jedi to add the import statement at the top of the file. So for example if I'm starting to type `os.`, I'll get completions for the `os` module even though it's not imported yet.

**Comment by davidhalter** [comment]
No. Doesn't work and will not work.

**Comment by infokiller** [comment]
Thanks for looking into this so quickly.
Do you have any suggestions how to work around that?

**Comment by davidhalter** [comment]
Write `import os` at the top. That's how you're supposed to write valid Python code.

**Comment by blueyed** [comment]
I could imagine making this work by adding (whitelisted) imports to the top of the file when passing the code to Jedi.
And then also having some magic on the Vim side to insert those lines actually.

But after all, it should probably only be the second thing: it would be too much magic to automatically import something just in the content being passed to Jedi.

Would it be possible to pass the current code (without the import) to Jedi and know from the result what imports are missing (because of ImportError for example)?

I'd like to have this feature, too.

@infokiller 
Do you think you could work on this?

It's not trivial of course.

**Comment by davidhalter** [comment]
> Would it be possible to pass the current code (without the import) to Jedi and know from the result what imports are missing (because of ImportError for example)?

No there's not. This would be a pretty big feature. It would probably need indexing.

**Comment by infokiller** [comment]
@blueyed 
I probably won't have time to do this right in the near future.
