### ISSUE TITLE
jedi-vim not smart enough

### ISSUE THREAD

**Issue by walkerlala** [davidhalter/jedi-vim#581]
Hi, I have some problem with the jedi-vim autocompletion.
I find that when jedi-vim is not able to autocomplete some *far away* variable. Examples:
```python
from lxml import etree
tree = etree.HTML(html_text)          #feed it some html
result = tree.xpath(xpath_pattern)   #cannot autocomplete here
```
you can see that, in line 3, when I type **tree.**, a autocomplete menu should pop up (I have configured that ) because **tree** does have a method called **xpath**.  If you do this ipython, it would autocomplete as you think. But things just does work in jedi-vim. It seem to not recognize those variable **far away** from home.
Is there any configuration that I missed?
Thanks!

**Comment by davidhalter** [comment]
Well, it's not fair to compare ipython with Jedi, because ipython has an advantage. Jedi btw will probably be IPython's completion engine in the future (which might take a few months still, but we are working on it). However in that case, Jedi can also use the advantage (exact Python objects).

Some things are just not working because they are too hard for static analysis (Python can be really complicated). The case here is exactly this case, xpath is just too complicated to understand if statically evaluated.

**Comment by walkerlala** [comment]
Which completion engine does Ipython use?

**Comment by walkerlala** [comment]
I understand the complication of python's syntax analyse. But, is there any configuration that make "another" completion work when jedi-vim doesn't ? I mean, when jedi-vim can't find anything to autocomplete, can I wake up the original autocompletion(which base on all the words in all the bufffer) so that when I hit a <Tab> it would at least give out some propoble completions ? I use superTab btw.

**Comment by davidhalter** [comment]
There might be something that supports this, I don't know. I have never used it. It's obviously possible to get word completion with another shortcut.

> Which completion engine does Ipython use?

It uses no engine at all, because it doesn't need one. You can also have completion to a certain degree in the normal python REPL. It basically just calls `dir()` on an object. Very simple.
