### ISSUE TITLE
Vim plug cannot install or update jedi-vim

### ISSUE THREAD

**Issue by spapanik** [davidhalter/jedi-vim#590]
When vim plug tries to install jedi-vim it calls ```git clone --depth 1 --no-single-branch --progress --recursive https://github.com/davidhalter/jedi-vim.git -b master jedi-vim```, which fails with:

Cloning into 'jedi-vim'...

remote: Counting objects: 97, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 97 (delta 22), reused 65 (delta 11), pack-reused 0
Unpacking objects: 100% (97/97), done.
Checking connectivity... done.
Submodule 'jedi' (https://github.com/davidhalter/jedi.git) registered for path 'jedi'
Cloning into 'xxxxxxxxxxxxxxx/jedi-vim/jedi'...
error: no such remote ref 995a6531225ba0b65e1ff863d97e5404d989047b
Fetched in submodule path 'jedi', but it did not contain 995a6531225ba0b65e1ff863d97e5404d989047b. Direct fetching of that commit failed.

**Comment by blueyed** [comment]
That's because of the `--depth 1` and is more a problem of vim-plug / your configuration then.
Using `--no-shallow-submodules` works also, but I think that Git itself should handle this (knowing which ref is meant to be checked out, and having support for shallow submodules)?!

Closing the issue for jedi-vim, but please keep us updated about the resolution of this.
Thanks.
