### ISSUE TITLE
Provide function to go to path provided as string

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#601]
You might have some settings that refer to some module/function as a string, e.g. 

```
        'DEFAULT_FILTER_BACKENDS': (
            'rest_framework.filters.DjangoFilterBackend',
        ),
```

It would be nice if `jedi#goto()` could handle this (when inside the string).

Additionally there could be a new function/command (`JediGoto`) where you could pass in a path to go to.

**Comment by davidhalter** [comment]
I think especially the `JediGoto` part would be really interesting.

I'm still not sure if string completion is such a good idea.

**Comment by davidhalter** [comment]
I personally don't think that this is a good idea anymore. I also think that this is quite complicated to work out.

However it's now possible to use `:Pyimport rest_framework.filters.DjangoFilterBackend`. I think this is a good middle ground, because with this change it's possible to implement your feature with a little bit of VIM script I guess.
