### ISSUE TITLE
Jedi rename turns syntax highlighting off

### ISSUE THREAD

**Issue by Tinche** [davidhalter/jedi-vim#65]
After performing a jedi-rename (leader-r), the syntax highlighting turns off. I have to turn it back on manually.

**Comment by syntonym** [comment]
In [`new_buffer()`](https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L530-L534) the comment  ("sometimes syntax is being disabled and the filetype not set.") sounds just like this bug. Although there is no syntax highlighting, `g:syntax_on` is set to true. This sounds like a bug in vim? In [`_tabnew()`](https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L539-L569) there is logic to switch to an existing tab instead of creating a new one. In [`new_buffer()`] there is no such logic, everytime `edit` is used. While I don't think `edit` should have such an effect, maybe switching to an existing buffer (with `:buffer`) would prevent that bug?

**Comment by davidhalter** [comment]
I have no idea. I'm pretty sure that it is a VIM bug. I have no idea where it is actually coming from and I'm too lazy to narrow it down.

**Comment by blueyed** [comment]
There have been fixes in this regard, especially https://github.com/davidhalter/jedi-vim/commit/e43012afc835e6db750ebbf299e452e9edb60f92.

So, does the problem still occur for you?

**Comment by syntonym** [comment]
I've not encountered the bug anymore, seems fixed for me.

**Comment by blueyed** [comment]
Cool, closing!
