### ISSUE TITLE
Add an option to sort the list of import completions by keywords in the current buffer

### ISSUE THREAD

**Issue by kovidgoyal** [davidhalter/jedi-vim#67]
Hi,

First, this is an awesome plugin, thank you for making it. One feature that would be useful is to have an option to sort the list of Import completions by keywords in the current buffer. An often used coding pattern (at least for me) is to use a name in the code then after wards go to the top of the file and import it. It would be nice if the import completion list put names that are already in the current buffer at the top. 

For example, suppose I am using PyQt

I have some code:

class MyDialog(QDialog):
   blah...

and later I do

from PyQt4.Qt import QD<C-x><C-o>

I currently get a very long list in which QDialog is far from the top.

**Comment by davidhalter** [comment]
Won't happen. I think that alphanumeric sorting is good enough for now. If someone implements this in Jedi, feel free. But there's no priority.

**Comment by ches** [comment]
For reference in case anyone takes a stab at it in the future:

It's not @kovidgoyal's original feature request in this issue, but the notion of an "organize imports" feature is also implied in the discussion—an implementation could quite possibly borrow from [flake8-import-order][1] which supports several styles.

Although maybe only in inspiration and not directly in code, because it's GPL…

[1]: https://github.com/PyCQA/flake8-import-order

**Comment by blueyed** [comment]
For sorting check out https://github.com/timothycrosley/isort/, too.
It can be easily integrated into Vim: https://github.com/blueyed/dotfiles/blob/f0aa2c334c86c6ec9fe9598012eaa052c7e6449c/vimrc#L2528.

I also found this snippet a while ago (which uses rope), not sure how good it is: http://pastebin.com/dzjexWGu.
