### ISSUE TITLE
ctrl + space doesn't work

### ISSUE THREAD

**Issue by MarounMaroun** [davidhalter/jedi-vim#677]
### Issue

I installed the plugin by cloning the git repo to `~/.vim/bundle` and then adding `set rtp+=~/.vim/bundle/jedi-vim` to my `~/.vimrc` file.

I also had to add this line:

```
autocmd FileType python setlocal omnifunc=jedi#completions
```

(are these steps fine for installation?)

When I type for example:

```python
import re
re.<ctrl> + <space>
```

nothing happens, but hitting `<ctrl> + x` followed by `<ctrl> + o`.

`:map` doesn't show the binding of `<ctrl> + x` and `<ctrl> + o`, so I'm not sure how that even works.

How can I make `<ctrl> + space` work for autocompletion?

### Versions

 - jedi-vim: latest (from master)
 - Vim / Neovim: 
 - Python: 2.7

**Comment by blueyed** [comment]
What does `verb set omnifunc?` give you?

**Comment by MarounMaroun** [comment]
@blueyed Nothing, I only see:

```
omnifunc=
```

**Comment by blueyed** [comment]
I understood that `<c-x><c-o>` would work?
It is the default trigger for omni completion in Vim - see `:h i_CTRL-X_CTRL-O`.

jedi-vim should configure both in https://github.com/davidhalter/jedi-vim/blob/7ddc50829eaa8350aa2bd60f4bb04e6620329b4f/after/ftplugin/python/jedi.vim#L5-L23.

Therefore you also need to add jedi-vim's `after` directory to `rtp` though.
To make it work properly (since the `after` dirs should come last etc) I recommend to use a proper plugin manager like vim-plug.

**Comment by MarounMaroun** [comment]
@blueyed got it, thanks.

**Comment by blueyed** [comment]
@MarounMaroun 
Could be added to the README (https://github.com/davidhalter/jedi-vim#manual-installation), in case you feel like creating a PR.

**Comment by MarounMaroun** [comment]
@blueyed Sure, I'll submit a PR soon.
