### ISSUE TITLE
jedi-vim requires vim>=7.4 (strictly, 7.3.1163) since #730 was merged

### ISSUE THREAD

**Issue by anntzer** [davidhalter/jedi-vim#764]
### Issue

#730 changed jedi-vim to load itself using the pythonx mechanism.  That mechanism was introduced in https://github.com/vim/vim/commit/c09a6d6, i.e. requires vim>=7.3.1163.  This is fine, but the docs currently state that vim>=7.3 is sufficient (https://github.com/davidhalter/jedi-vim/blob/master/doc/jedi-vim.txt) and thus need to be edited accordingly.

### Steps to reproduce

Trying to use jedi.vim in vim 7.3 results in a failure to import jedi_vim.

### Output of “:verbose JediDebugInfo”

N/A

**Comment by davidhalter** [comment]
I would argue that we should just improve the documentation. IMO supporting 7.3 will also be hard because we don't really use it anymore.

**Comment by blueyed** [comment]
Sorry for missing this back then - it would not be too hard to use python2/python3 again I guess, but other incompatibilities might have sneaked in elsewhere anyway already, and I agree that we probably just have a clear(er) error message in this case, and update the docs.

**Comment by davidhalter** [comment]
Yeah, I just went through quite a few old issues and I'm realizing how much important things I missed. But I cannot do everything, unfortunately. I agree that documentation is the way to go.

**Comment by davidhalter** [comment]
I realized that I simply don't know what we support. I have never known and I probably will never know, because I don't have access to arbitrary VIM versions and I also don't want to document something that is invalid the next time something is merged. So I'm closing.

I know that this situation is not perfect. Not at all. However, I feel like it's pretty hard for me to improve it and I wouldn't want to spend a lot of time on it.
