### ISSUE TITLE
Make jedi vim use the cache for completions

### ISSUE THREAD

**Issue by jakab922** [davidhalter/jedi-vim#776]
Is there a way to make jedi-vim use the `~/.cache/jedi` directory or even better(since I use virtualenvs) tell jedi-vim to use a specific directory when making completions?

I mean once they are loaded the completions work just fine. The issue is that the first time a package is used it can take ages(pandas) to cache the completions. Although between two subsequent runs this work is lost since it needs to rebuild the cache once again. Is there a way to avoid this?

**Comment by davidhalter** [comment]
This question has nothing to  do with jedi-vim but is all about jedi.

The problem is not that the cache is regenerated, but the cache is loaded. I don't see a way at the moment to make loading this cache faster.

I'm considering switching to something like a database for these things, but that's like a year away.

With asynchronous completions you might also be less annoyed about it taking ages, but that's not what jedi-vim does at the moment.

**Comment by jakab922** [comment]
Maybe jedi could run as a service. Storing it in a database is a good idea imho. Can I help?

**Comment by davidhalter** [comment]
It is a good idea, but it's a lot of work. I think I would need probably like 4 months full time (at least) to create a good database index. There are just so many pitfalls.

There's always stuff to do. :) Fixing bugs and merging pull requests is my first priority. If I don't clean all those things up first, it will haunt me when implementing more advanced features.
