### ISSUE TITLE
please consider tagging new releases on git

### ISSUE THREAD

**Issue by anthraxx** [davidhalter/jedi-vim#787]
Hi, thanks for the awesome plugin.
I would really appreciate if you could start tagging releases again. The last one is from 2015.
Its not much work and its reallt a good thing to have a tag from developers when they know enough fixes or features went into development plus it feels to be stable right now.
thanks a lot!

**Comment by anthraxx** [comment]
did you make your mind on this? packages are shpping a very ancient version and its really just a easy two-command thingie (tagging + push) thats all. There are literally no downsides doing so on a semi regular base.
nobody needs or expects enterprise QA ensurence just because there are tags :joy_cat:

**Comment by davidhalter** [comment]
I pushed a new one with current master. It's probably not perfect, but fine.

I don't really do releases, because of laziness. Just kick me again if it's an issue!

@blueyed I hope you don't mind, but since we never really broke backwards compatibility and most things were just bugfixes and general improvements I hope you don't mind.

**Comment by blueyed** [comment]
@davidhalter 
Sure, and thanks!

**Comment by anthraxx** [comment]
awesome :tada: 
thank you very much i really appreciate it. I will ping you again if i notice it would make sense again :cat: 
keep it up, love vim-jedi
