### ISSUE TITLE
Cached completions are still slow with numpy (after being cached)

### ISSUE THREAD

**Issue by darthdeus** [davidhalter/jedi-vim#824]
The README says:

> Completion of complex libraries (like Numpy) should only be slow the first time you complete them. After that the results should be cached and very fast.

But on my i7-5820k, the completion after the first one (and all the ones after that) take roughly 3 seconds on Numpy. I'm not using rope, and nothing else is really running on the system.

I'm confused, is this considered very fast, or is it a performance regression since the README was written? Because 3 seconds when the editor freezes completely any time I type a `.` feels anything but _very fast_.

Is there any way to improve the performance? Or any idea what is the bottleneck?

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there fore a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
