### ISSUE TITLE
AttributeError: 'FStringStart' object has no attribute 'children' (/pythonx/jedi/jedi/evaluate/syntax_tree.py?)

### ISSUE THREAD

**Issue by yryrgogo** [davidhalter/jedi-vim#881]
### Issue
Completion doesn't work, and typing dots gives an error.
example...
> import numpy as np
> np.  

=> Error and completion doesn't work.

#### Error Message
> AttributeError: 'FStringStart' object has no attribute 'children'

### Output of “:verbose JediDebugInfo”

Probably I think the following Python code is giving an error.
> /pythonx/jedi/jedi/evaluate/syntax_tree.py 
> :337 
> iterator = iter(or_test.children)

#### My environment
Ubuntu 16.04
neovim==0.2.6
python 3.6.3 (Anaconda)
Jedi: 0.13.1

I have few information, but please let me know if it is not enough.
Also, my other Jedi 0.11.1 in a similar environment is working.

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
