### ISSUE TITLE
Autocomplete for imports doesn't work properly

### ISSUE THREAD

**Issue by artem0** [davidhalter/jedi-vim#917]
Autocomplete for imports doesn't work

Autocomplete works fine after declaration of import, for example:

```
import os
os.p // it works fine
```

But it doesn't work properly in import section:

```
import os.p // it doesn' work

from datetim // doesn't work
from datetime. // also doesn't work
```

##### jedi-vim version

 - jedi-vim git version: 1f7e661
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)
 - parso git submodule status:  acccb4f28d6d57f4ad4c882f3408136ee8f50ff5 pythonx/parso (v0.3.4)

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
