### ISSUE TITLE
Confliction with Valloric/vim-operator-highlight

### ISSUE THREAD

**Issue by pokemonchw** [davidhalter/jedi-vim#957]
### Issue

This problem is the same as [issue](https://github.com/davidhalter/jedi-vim/issues/639)
It has been [fixed](https://github.com/davidhalter/jedi-vim/pull/646)
But now I saw "=`=jedi=0, =`=(file, keys) =`=jedi=`=" again.

**Comment by blueyed** [comment]
Try https://github.com/davidhalter/jedi-vim/pull/652 maybe.

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
