### ISSUE TITLE
No autocomplete after variable assignment

### ISSUE THREAD

**Issue by omaranbari** [davidhalter/jedi-vim#961]
### Issue

Let's say I create: df = pd.DataFrame()

If I write df. immediately after the declaration, I get the expected auto-completion.

Now If I assign the variable, for instance by writing df = pd.read_excel('some/file/path.xlsx'), and on the subsequent line I type df. , I don't get any jedi auto-completion.

### Steps to reproduce

1. Declare variable as: df = pd.DataFrame()
2. type df. and wait for autocompletion
3. Assign variable as: df = pd.read_excel('some-file.xlsx')
4. type df. , wait for auto completion, doesn't show up

**Comment by davidhalter** [comment]
I'm closing this, because it's very unlikely this ever gets fixed. The code in https://github.com/pandas-dev/pandas/blob/master/pandas/io/excel/_base.py#L281 is quite complicated. If you can easily show me how the return type can be inferred (even I myself am not able to do that, and I'm not a machine), I might reopen. I'm really struggling to understand what is returned there. After about 10 minutes of looking at code, I think I found the reason why it's probably not working: https://github.com/pandas-dev/pandas/blob/6c0e09f148eb1029bfe56495f003b574ad629800/pandas/io/excel/_base.py#L398. Basically they do dict modifications and then read from the dict again, so it's just very complicated to understand that. The return type in the end comes from here: https://github.com/pandas-dev/pandas/blob/6c0e09f148eb1029bfe56495f003b574ad629800/pandas/io/parsers.py#L1160.

However in cases like this, I recommend you to push the pandas guys to adopt annotations or typing stubs in such places, so Jedi understands what is happening.
