### ISSUE TITLE
cannot autocomplete the python3 style defination

### ISSUE THREAD

**Issue by zYeee** [davidhalter/jedi-vim#971]
```
class Solution:
    def stoneGame(self, piles: List[int]) -> bool:
        pass

s = Solution()
s.
```

after I press '.', it would not complete the function stoneGame for me.
But if I use python2 style, it can work:

```
def stoneGame(self, piles):
        pass
```

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
