### ISSUE TITLE
gibberish autocomplete

### ISSUE THREAD

**Issue by GianniGi** [davidhalter/jedi-vim#983]
### Issue
the addon autocompletes what I'm about to type in a way that I don't understand, for example it just added this monstrosity when I tried to add a dot at the end of the list "vettore".
    vettore.e_opened(1)
    telpmoc#idej=

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.
