### ISSUE TITLE
 Suppress docstring window during autocomplete

### ISSUE THREAD

**Issue by GianniGi** [davidhalter/jedi-vim#987]
I've tried this but it does nothing...
https://github.com/davidhalter/jedi-vim/issues/168

any help? 
I don't want to see the popup with the docstrings, which hide my code. It's ok to see the documentation in the split buffer, I'd like to remove just that popup.

thanks

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by blueyed** [comment]
To be fair this does not really need all the debugging info etc, but also qualifies at "debugging vim config" I think.
For reference, the FAQ: https://github.com/davidhalter/jedi-vim#i-dont-want-the-docstring-window-to-popup-during-completion

**Comment by davidhalter** [comment]
The problem with these is that I'm not sure what they already did and what they didn't. I don't know if `-= preview` was already done. I also don't know if they have an extremely weird VIM version or some other setup we might not know about.

So generally I just scan the debugging info and it helps me to rule out some things. Posting the debug info is less than a minute of work and I feel like people should be able to just do that.
